name: Molsoft themes QA step

on:
  pull_request_review:
    types: [submitted]

jobs:
  context:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
   
  build:
    if: (github.event.pull_request.base.ref == 'development' || github.event.pull_request.base.ref == 'Development') && github.event.review.state == 'approved'
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - uses: actions/setup-node@v2
        
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS:  

      - name: Install ThemeKit
        run: curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install.py | sudo python

      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.PAT }}

      - name: install molsoft-tools
        run: sudo npm i -g molsoft-io/molsoft-tools --unsafe-perm=true
        
      - name: install dependencies
        run: sudo npm i

      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy theme to QA
        if: ${{ success() }}
        run: molsoft-tools deploy --env=qa

      - name: yamler
        uses: juliojimenez/yamler@v0
        id: yamler
        with:
          yaml-file: "config.yml"

      - run: echo "${{ toJson(steps.yamler) }}"
      - name: Slack Notification Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: qa
          SLACK_ICON: https://avatars3.githubusercontent.com/u/75539895
          SLACK_MESSAGE: 'QA Theme is ready for preview at https://${{ steps.yamler.outputs.qa__store }}?preview_theme_id=${{ steps.yamler.outputs.qa__theme_id }} :rocket:'
          SLACK_TITLE: Message
          SLACK_USERNAME: Molsoft Automation
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack notification failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: qa
          SLACK_COLOR: "danger"
          SLACK_ICON: https://avatars3.githubusercontent.com/u/75539895
          SLACK_MESSAGE: 'Oh no, something happened! :disappointed: Take a look at the action to see the issue.'
          SLACK_TITLE: Message
          SLACK_USERNAME: Molsoft Automation
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}