name: Molsoft themes Production step

on:
  pull_request_review:
    types: [submitted]
    
  workflow_dispatch:
    inputs:
      skipSync:
        description: 'Skip repo sync(Set to true if you fixed merge conflicts)'
        default: "false"
    
jobs:
  context:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
  build:
    if: (github.event_name == 'workflow_dispatch' || (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'master') && github.event.review.state == 'approved')
    runs-on: ubuntu-18.04
    
    steps: 
      - uses: actions/setup-node@v2

      # persist crendentials is set to false
      # so that we can set our own acces token for fregante/setup-git-token@v1
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: main

      # Line endings with themekit download are inconsistent
      # it can be LF for a theme and CRLF for another
      # We install dos2unix to convert to LF everything after downloading a theme.
      - name: "Download dos2unix for help with line endings"
        run: |
          sudo apt-get install dos2unix
      - name: yamler
        uses: juliojimenez/yamler@v0
        id: yamler
        with:
          yaml-file: "config.yml"

      - name: Install ThemeKit
        run: curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install.py | sudo python

      # We need a personnal access token to install private repositories
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.PAT }}

      - name: install molsoft-tools
        run: sudo npm i -g molsoft-io/molsoft-tools --unsafe-perm=true

      # Then we checkout again in main with persist-credentials true
      # because stefanzweifel/git-auto-commit-action@v4 Only works with 
      # the credential created by actions/checkout@v2
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          ref: main
          token: ${{ secrets.PAT }}
        
      # we download the live theme into a temp folder to create a backup
      # and do molsoft-tools download to sync the repo with the live theme 
      # ("molsoft-tools download" download the theme while excluding files generated by webpack)
      - name: Download live theme into main
        run: |
          mkdir temp
          molsoft-tools download --env=production
          theme download --env=production --dir="temp" --password=${{ steps.yamler.outputs.production__password }} --store=${{ steps.yamler.outputs.production__store }} --themeid=${{ steps.yamler.outputs.production__theme_id }}
      - name: Convert to LF line endings
        run: find . -type f -print0 | xargs -0 dos2unix
        
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YY/MM/DD HH:mm A
          utcOffset: "-05:00"
        
      - name: Deploy backup theme
        run: |
          theme new --env=backup --dir="temp" --password=${{ steps.yamler.outputs.production__password }} --store=${{ steps.yamler.outputs.production__store }} --name="Molsoft backup - ${{ steps.current-time.outputs.formattedTime }}"
          sudo rm -r ./temp
        
      - name: Sync main with live theme
        if: github.event.inputs.skipSync != 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sync with live theme
          commit_user_name: Molsoft Automations
          commit_user_email: hello@molsoft.io
      
      - name: checkout Development
        uses: actions/checkout@v2
        with:
          ref: Development
          token: ${{ secrets.PAT }}
          
      - name: Download QA theme
        if: github.event.inputs.skipSync != 'true'
        run: molsoft-tools download --env=qa

      - name: Convert to LF line endings
        run: find . -type f -print0 | xargs -0 dos2unix
        
      # Some little things could have been added by integrators. This is why we sync the repo with the QA theme
      - name: Sync development with QA theme
        if: github.event.inputs.skipSync != 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sync with QA theme
          commit_user_name: Molsoft automations
          commit_user_email: hello@molsoft.io
        
      - name: Merge development into main
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: 'Development'
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

      - name: Merge main into development
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: 'Development'
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
          
      - name: checkout main
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: main
        
      - name: install dependencies
        run: sudo npm i

      - name: Deploy theme to Production
        run: molsoft-tools deploy --env=production

      - name: Slack Notification Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: qa
          SLACK_ICON: https://avatars3.githubusercontent.com/u/75539895
          SLACK_MESSAGE: 'The theme was published live :rocket: You can see it here: https://${{ steps.yamler.outputs.qa__store }}'
          SLACK_TITLE: Message
          SLACK_USERNAME: Molsoft Automation
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack notification failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: qa
          SLACK_COLOR: "danger"
          SLACK_ICON: https://avatars3.githubusercontent.com/u/75539895
          SLACK_MESSAGE: 'Oh no, something happened! :disappointed: Take a look at the action to see the issue.'
          SLACK_TITLE: Message
          SLACK_USERNAME: Molsoft Automation
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
